version: '3'

tasks:
  control:
    cmds:
      - go run shadowglass/cmd/control

  agents:
    ignore_error: true
    cmds:
      - GOOS=linux GOARCH=arm64 go build -o build/agent shadowglass/cmd/agent
      - docker compose up

# vim: ts=4 sts=4 sw=4 et
