version: '3'

tasks:
  control:
    cmds:
      - go run github.com/shadowglass-xyz/prism/cmd/control

  agent:
    env:
      CONTROL_PLANE_URL: http://localhost:4222
    ignore_error: true
    cmds:
      - go run github.com/shadowglass-xyz/prism/cmd/agent

  tui:
    cmds:
      - go run github.com/shadowglass-xyz/prism/cmd/tui

# vim: ts=2 sts=2 sw=2 et
