# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "demo-debian1" do |debian|
    debian.vm.hostname = "debian1"
    debian.vm.box = "bento/debian-11"
    debian.vm.network "private_network", ip: "192.168.33.10"
    debian.vm.provision "shell", inline: <<-SHELL
      curl https://get.docker.com | sh -
      sudo usermod -aG docker vagrant
      sudo apt install tmux neovim

      curl -sf https://binaries.nats.dev/nats-io/natscli/nats@latest | PREFIX=/usr/local/bin sh

      wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt-get update && sudo apt-get install consul
    SHELL
  end

  config.vm.define "demo-debian2" do |debian|
    debian.vm.hostname = "debian2"
    debian.vm.box = "bento/debian-11"
    debian.vm.network "private_network", ip: "192.168.33.11"
    debian.vm.provision "shell", inline: <<-SHELL
      curl https://get.docker.com | sh -
      sudo usermod -aG docker vagrant
      sudo apt install tmux neovim

      curl -sf https://binaries.nats.dev/nats-io/natscli/nats@latest | PREFIX=/usr/local/bin sh

      wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt-get update && sudo apt-get install consul
    SHELL
  end
end
